config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :patients
  end
  get '/locations/:id' => "locations#show", :as => "location"
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :patients
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	after_create :mr_after_create
	belongs_to :location
	default_scope { where(is_deleted: false) }
	scope :onTreatment,  -> { where(status: 3) }


	private
		def mr_after_create
			mr = self.id.to_s
		    pre_fix = 6 - mr.length
		    pre_fix.times {mr.insert(0, '0')} if pre_fix
		    self.medical_record_number = mr
			self.save
		end
end

app/controllers/admin/patients_controller.rb
class Admin::PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    respond_to do |format|
      if @patient.save
        format.html { redirect_to admin_patient_path(@patient), notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to admin_patient_path(@patient), notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.is_deleted = 1
    @patient.save
    respond_to do |format|
      format.html { redirect_to admin_patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :middle_name, :last_name, :year, :month, :day, :gender, :status, :location_id, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # I18n.default_locale = 'zh-CN'
  before_action :set_locale
 
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
	# handler of Medical Record number
	def showMR(text)
		text.insert(0, 'MR') if text.length>0
	end

	# handler of gender
	def showGender(text)
		case text
		when 1
			text = t("patinet.Male")
		when 2
			text = t("patinet.Female")
		else
			text = t("patinet.not_available")
		end
	end

	# handler of status
	def showStatus(text)
		case text
		when 1
			text = t("patinet.Initial")
		when 2
			text = t("patinet.Referred")
		when 3
			text = t("patinet.Treatment")
		when 4
			text = t("patinet.Closed")
		else
			text = ''
		end
	end

	# select data
	def selectData(text)
		case text
		when :gender
			data = [[t("patinet.not_available"), 0], [t("patinet.Male"), 1], [t("patinet.Female"), 2]]
		when :status
			data = [[t("patinet.Initial"), 1], [t("patinet.Referred"), 2], [t("patinet.Treatment"), 3], [t("patinet.Closed"), 4]]
		when :location_id
			hash = {}
			locations = Location.all
			locations.each do |i|
				hash[i.name] = i.id
			end
			data = hash.to_a
		end
	end

	def I18nChange(text,type)
		text
		flag = text.include? '?locale'
		if flag
			limit = text.index("?locale")
			text = text[0,limit] << "?locale=#{type}"
		else
			text << "?locale=#{type}"
		end
	end
end

app/views/admin/patients/_form.html.erb
<style type="text/css">
  .change_width{
    width: 20%;
    float: left;
    margin-right: 20px;
  }
</style>

<%= form_for [:admin, @patient], :html => { :class => "form-horizontal patient" } do |f| %>

  <% if @patient.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @patient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :first_name, :required => true, :size => 30, :class => 'form-control' %>
    </div>
    <%=f.error_span(:first_name) %>
  </div>
  <div class="form-group">
    <%= f.label :middle_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :middle_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:middle_name) %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_name, :required => true, :size => 30, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_name) %>
  </div>

  <div class="form-group">
    <%= f.label :date_of_birth, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :year, {}, {}, class: "sel_year form-control change_width", rel: @patient.year %>
      <%= f.select :month, {}, {}, class: "sel_month form-control change_width", rel: @patient.month %>
      <%= f.select :day, {}, {}, class: "sel_day form-control change_width", rel: @patient.day %>
    </div>
    <%=f.error_span(:year) %>
  </div>

  <div class="form-group">
    <%= f.label :gender, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
    <div class="form-control" style="height:auto;border:none;padding:0px 20px;border-radius: 0px;">
        <div class="radio">
          <%= f.radio_button :gender, 0, :checked => true %><%= t("patinet.not_available") %>
        </div>
        <div class="radio">
          <%= f.radio_button :gender, 1 %><%= t("patinet.Male") %>
        </div>
        <div class="radio">
          <%= f.radio_button :gender, 2 %><%= t("patinet.Female") %>
        </div>
    </div>
    </div>
    <%=f.error_span(:gender) %>
  </div>

  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :status, selectData(:status), {}, class: "form-control change_width" %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :location_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :location_id, selectData(:location_id), {}, class: "form-control change_width" %>
    </div>
    <%=f.error_span(:location_id) %>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_patients_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  $(function () { 
    $.ms_DatePicker({ 
            YearSelector: ".sel_year", 
            MonthSelector: ".sel_month", 
            DaySelector: ".sel_day" 
    }); 
  });
</script>

app/views/admin/patients/edit.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/patients/index.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:full_name) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:viewed_count) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to patient.id, admin_patient_path(patient) %></td>
        <td><%= showMR(patient.medical_record_number) %></td>
        <td><%= patient.first_name+' '+patient.middle_name+' '+patient.last_name %></td>
        <% 
          y   = patient.year.to_i
          age = t("patinet.undefined")
          if y > 0
            age = Time.new.year - y
          end
        %>
        <td><%= age %></td>
        <td><%= showGender(patient.gender) %></td>
        <td><%= showStatus(patient.status) %></td>
        <td><%= patient.viewed_count %></td>
        <td><%= link_to patient.location.name, location_path(patient.location) , {:title => t("patinet.rftl")} %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_patient_path(patient), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_patient_path(patient),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_patient_path,
            :class => 'btn btn-primary' %>

app/views/admin/patients/new.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/patients/show.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @patient.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:middle_name) %>:</strong></dt>
  <dd><%= @patient.middle_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @patient.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:medical_record_number) %>:</strong></dt>
  <dd><%= showMR(@patient.medical_record_number) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= @patient.year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:month) %>:</strong></dt>
  <dd><%= @patient.month %></dd>
  <dt><strong><%= model_class.human_attribute_name(:day) %>:</strong></dt>
  <dd><%= @patient.day %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
  <dd><%= showGender(@patient.gender) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= showStatus(@patient.status) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location_id) %>:</strong></dt>
  <dd><%= @patient.location.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:viewed_count) %>:</strong></dt>
  <dd><%= @patient.viewed_count %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_deleted) %>:</strong></dt>
  <dd><%= @patient.is_deleted %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @patient.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
  <dd><%= @patient.created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:updated_at) %>:</strong></dt>
  <dd><%= @patient.updated_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_patients_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_patient_path(@patient), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_patient_path(@patient),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MrCool" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">MrCool</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Patient", admin_patients_url  %></li>
            <li><%= link_to "Wiki", "/path2"  %></li>
            <li><%= link_to "Notice", "/path3"  %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "中文", I18nChange(request.url,'zh-CN') %></li>
            <li><%= link_to "English", I18nChange(request.url,'en')  %></li>
            <li><%= link_to "SingIn", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <div id="notice">
            <%= bootstrap_flash %>
          </div>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "AllPatients", "/path1"  %></li>
              <li><%= link_to "MyPatients", "/path2"  %></li>
              <li><%= link_to "onTreatment", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016 <%= t('sohotdai') %></p>
      </footer>

    </div> <!-- /container -->
    <script type="text/javascript">
      var hideNotice = function(){
          $("#notice").fadeOut("slow");
      }
      setTimeout(hideNotice, 2000);
    </script>
  </body>
</html>